/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE 
WHERE SEXO = 'M';

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

/* UTILIZANDO O LIKE */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

/* CARACTER CORINGA % */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

/* OPERADORES LÓGICOS */
/* OU - OU */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, EMAIL FROM CLIENTE
WHERE 
SEXO = 'F' OR ENDERECO LIKE '%MG';

/* AND - E */

SELECT NOME, EMAIL FROM CLIENTE
WHERE 
SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'F' AND ENDERECO LIKE '%RJ';

/* COUNT(*), GROUP BY, PERFORMANCE COM OPERADORES LOGICOS */
/* CONTANDO OS REGISTROS DA TABELA */

SELECT COUNT(*)FROM CLIENTE;

SELECT COUNT(*) AS "QUANTIDADE" FROM CLIENTE;

/* OPERADOR GROUP BY */

SELECT SEXO, COUNT(*) AS "QUANTIDADE"
FROM CLIENTE 
GROUP BY SEXO;


/* PERFORMANCE EM OPERADORES LOGICOS */
/* 1 MILHAO DE REGISTROS

PARA CONTAR 
SELECT COUNT(*) FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE
GROUP BY SEXO;

SELECT CIDADE, COUNT(*) FROM CLIENTE
GROUP BY CIDADE;

CONDICAO
SEXO = F 
CIDADE = RIO DE JANEIRO 



/* FILTRANDO VALORES NULOS */

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE EMAIL IS NULL;


/* UTILIZANDO UPDATE PARA ATUALIZAR VALORES */

SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'LILIAN@HOTMAIL.COM';

/* SEMPRE USAR UPDATE COM A CLAUSULA WHERE */

UPDATE CLIENTE
SET EMAIL = 'JORGE@HOTMAIL.COM'
WHERE NOME = 'JORGE';

/* DELETANDO REGISTROS COM A CLAUSULA DELETE, SEMPRE COM WHERE */

DELETE FROM CLIENTE; ---------- NUNCA FAZER ----------

SELECT COUNT(*) FROM CLIENTE;

DELETE FROM CLIENTE 
WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE;

/* CARDINALIDADE - QUEM DEFINE É A REGRA DE NEGÓCIOS */
/* PRIMEIRO ALGARISMO - OBRIGATORIEDADE 
0 - NAO OBRIGATORIO
1 - OBRIGATORIO

SEGUNDO ALGARISMO - CARDINALIDADE 
1 - MAXIMO DE UM
N - MAIS DE UM 
*/