/* FUNCOES DE AGREGACOES NUMERICAS */

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR (1), 
	JANEIRO FLOAT(10,2),
	FEVEREIRO FLOAT(10,2),
	MARCO FLOAT(10,2)
);

INSERT INTO VENDEDORES VALUES(NULL,'ANDERSON','M',22900.38,30400.87,42345.85);
INSERT INTO VENDEDORES VALUES(NULL,'JOEL','M',12400.38,30200.87,51445.85);
INSERT INTO VENDEDORES VALUES(NULL,'LAURA','F',12300.38,37800.87,74545.85);
INSERT INTO VENDEDORES VALUES(NULL,'EDGAR','M',95600.38,305600.87,74645.85);
INSERT INTO VENDEDORES VALUES(NULL,'MARIA','F',54600.38,23400.87,54345.85);
INSERT INTO VENDEDORES VALUES(NULL,'RENAN','M',23400.38,45400.87,34545.85);
INSERT INTO VENDEDORES VALUES(NULL,'CLARA','F',18900.38,74800.87,32145.85);
INSERT INTO VENDEDORES VALUES(NULL,'ANA','F',24600.38,94600.87,12345.85);

/* MAX - TRAZ O VALOR MAXIMO DE UMA COLUNA */

SELECT MAX(FEVEREIRO) AS MAIOR_FEV
FROM VENDEDORES;

/* MIN - TRAZ O VALOR MINIMO DE UMA COLUNA */

SELECT MIN(FEVEREIRO) AS MENOR_FEV
FROM VENDEDORES;

/* AVG - TRAZ O VALOR MEDIO DE UMA COLUNA */

SELECT AVG(FEVEREIRO) AS MEDIA_FEV
FROM VENDEDORES;

/* VARIAS FUNCOES */

SELECT MAX(JANEIRO) AS MAX_JAN,
	   MIN(JANEIRO) AS MIN_JAN,
	   TRUNCATE (AVG(JANEIRO),2) AS MEDIA_JAN
	   FROM VENDEDORES;
	  
/* FUNCAO TRUNCATE */
SELECT MAX(JANEIRO) AS MAX_JAN,
	   MIN(JANEIRO) AS MIN_JAN,
	   TRUNCATE (AVG(JANEIRO),2) AS MEDIA_JAN
	   FROM VENDEDORES;
	   
/* AGREGANDO COM A FUNCAO SUM() - SOMA OS VALORES DE UAM COLUNA */ 

SELECT SUM(JANEIRO) AS TOTAL_JAN,
	   SUM(FEVEREIRO) AS TOTAL_FEV,
	   SUM(MARCO) AS TOTAL_MAR
FROM VENDEDORES;

/* VENDAS POR SEXO */

SELECT SEXO, SUM(MARCO) AS TOTAL_MARCO
FROM VENDEDORES
GROUP BY SEXO;

/* SUBQUERIES */

/* VENDEDOR QUE VENDEU MENOS EM MARCO E SEU NOME */

SELECT MIN(MARCO) FROM VENDEDORES;

V

SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

/* VENDEDOR QUE VENDEU MAIS EM MARCO E SEU NOME */

SELECT MAX(MARCO) FROM VENDEDORES;

V

SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

/* VENDEDOR QUE VENDEU MAIS QUE O VALOR MEDIO DE FEVEREIRO */
SELECT NOME, FEVEREIRO FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);