/* IFNULL */

SELECT C.NOME, 
	   IFNULL( C.EMAIL,'SEM EMAIL')  <------
	   T.NUMERO
FROM CLIENTE C
INNER JOIN TELEFONE  T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE TIPO = 'CEL' AND ESTADO = 'RJ';