========= /* CRIANDO NOVA TABELA */ =========




CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('COM','RES','CEL' ),
	NUMERO VARCHAR(10),
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

/* FOREIGN KEY - CHAVE ESTRANGEIRA - FK */
/* É A CHAVE PREIMARIA DE UMA TABELA, QUE VAI ATE
OUTRA TABELA FAZER REFERENCIA */

/* EM RELACIONAMENTOS 1 X 1, A CHAVE ESTRANGEIRA
FICA NA TABELA MAIS FRACA */

/* EM RELACIONAMENTOS 1 X N, A CHAVE
ESTRANGEIRA FICARA SEMPRE NA TABELA N */

/* FAZENDO OS INSERTS - CLIENTES*/

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAO@IG.COM','98547-6');
INSERT INTO CLIENTE VALUES(NULL,'RENAN','M','RENAN@TERRA.COM','86664-7');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@GLOBO.COM','75658-5');
INSERT INTO CLIENTE VALUES(NULL,'JONAS','M','JONAS@IG.COM','88657-5');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'99754-7');
INSERT INTO CLIENTE VALUES(NULL,'CECILIA','F','CECILIA@TERRA.COM','77558-5');

SELECT * FROM CLIENTE;

/* FAZENDO OS INSERTS - ENDERECO*/

 INSERT INTO ENDERECO VALUES(NULL,'RUA A','CENTRO','ERECHIM','RS',1);
 INSERT INTO ENDERECO VALUES(NULL,'RUA B','SAO CAETANO','ERECHIM','RS',2);
 INSERT INTO ENDERECO VALUES(NULL,'RUA C','CENTRO','RIO DE JANEIRO','RJ',3);
 INSERT INTO ENDERECO VALUES(NULL,'RUA D','JARDINS','SAO PAULO','SP',4);
 INSERT INTO ENDERECO VALUES(NULL,'RUA E','LINHO','ERECHIM','RS',5);
 INSERT INTO ENDERECO VALUES(NULL,'RUA F','DUENDE','PASSO FUNDO','RS',6);

SELECT * FROM ENDERECO;

/* FAZENDO OS INSERTS - TELEFONE*/

INSERT INTO TELEFONE VALUES(NULL,'CEL','123456789',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','12345624',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','12345645',6);
INSERT INTO TELEFONE VALUES(NULL,'RES','12345583',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','12349852',3);
INSERT INTO TELEFONE VALUES(NULL,'RES','12316385',5);

SELECT * FROM CLIENTE;
SELECT * FROM ENDERECO;
SELECT * FROM TELEFONE;

/* JOIN - JUNCAO - 2 TABELAS */

SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE 
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE
WHERE SEXO  = 'M';

/* JOIN - JUNCAO - 3 TABELAS */

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, 
ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

/* FORMA PRATICA - APELIDOS */

SELECT C.NOME, C.SEXO, E.BAIRRO, 
E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

-----------------------------

SELECT C.NOME, C.SEXO, E.BAIRRO, 
E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';

/* ESTUDANDO AS QUERIES */

SELECT C.NOME, C.EMAIL, T.NUMERO
FROM CLIENTE C
INNER JOIN TELEFONE  T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE TIPO = 'CEL' AND ESTADO = 'RJ';


+------+---------------+-----------+
| NOME | EMAIL         | NUMERO    |
+------+---------------+-----------+
| ANA  | ANA@GLOBO.COM | 123456789 |
| ANA  | ANA@GLOBO.COM | 12349852  |
+------+---------------+-----------+