/* CRIANDO PROCEDURES */

---> SEMPRE INICIAR MUDANDO O DELIMITADOR 

DELIMITER $

CREATE PROCEDURE NOME()
BEGIN
		ACAO;
END
$

SELECT 10 + 10 AS 'CONTA'$

CREATE PROCEDURE CONTA()
BEGIN	
		SELECT 10 + 10 AS 'CONTA';
END
$

/* CHAMANDO UMA PROCEDURE */

CALL CONTA()$

/* PROCEDURES COM PARAMETROS */
/* APAGANDO PROCEDURE */

DROP PROCEDURE CONTA$

/* COM PARAMETROS */

CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN	
		SELECT NUMERO1 + NUMERO2 AS 'CONTA';
END
$

CALL CONTA(100,78)$
CALL CONTA(13,4564)$
CALL CONTA(2342,4654)$

/* PROCEDURES COM TABELAS */

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
)$

INSERT INTO CURSOS VALUES(NULL,'BANCO DE DADOS FUNDAMENTAL',25,200.00)$

SELECT * FROM CURSOS$


CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30),P_HORAS INT(3),P_PRECO FLOAT(10,2))
BEGIN 
		INSERT INTO CURSOS VALUES(NULL, P_NOME,P_HORAS,P_PRECO);
END
$


CREATE PROCEDURE SEL_CURSO()
BEGIN
		SELECT IDCURSO, NOME, HORAS, VALOR
		FROM CURSOS;
END
$

CALL SEL_CURSO()$
